baseURL: https://darshan701.github.io # todo: change site url.
title: Darshan # todo: change site name.
defaultContentLanguage: 'en'
theme: eternity
googleAnalytics: '' # todo: set your analytics id.

params:
  image: /images/banner.png
  subtitle: Eternity is a minimalist Hugo theme designed for portfolio sites with a fresh feel. # todo: change default subtitle for your website.
  dontShowSource: false # please, do not do this :)
  portfolio:
    columns:
      desktop:
        nature: 4
        archive: 6
        people: 2
        default: 3
      mobile:
        default: 2
        archive: 3
        people: 1
  socials:
    # todo: change these links.
    - icon: 'far fa-envelope fa-lg'
      url: 'mailto:hello@darshan.digital'
      landing: true
    - icon: 'fab fa-instagram fa-lg'
      url: 'https://www.instagram.com/darshan.__.krishna/'
      landing: true
    - icon: 'far fa-twitter fa-lg'
      url: 'https://twitter.com/DJ_Games001'
      landing: true
    - icon: 'far fa-cube fa-lg'
      url: 'https://www.cgtrader.com/dj-games'
      landing: true

  homepage: "work" # homepage link, mostly same with menu.main[0]
  specialPages:
    - work
    - archive
  bypassWelcomePage: false # redirects "/" to "homepage" when it's true.
  plausible: '' # todo: set your plausible id.
  disableRadius: false
  moveIt: false  # Moves Title and Meta info down, only visible when scroll.

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: tags

permalinks:
  work: ":filename/"

menu:
  main:
    - name: work
      url: /work/
      weight: 1 
    - name: sci-fi
      url: /tags/sci-fi
      weight: 2
    - name: horror
      url: /tags/horror
      weight: 3
    - name: dreamy
      url: /tags/dreamy
      weight: 4
    - name: about
      url: /about/
      weight: 5
